# Generated by Django 3.2.22 on 2023-10-31 04:36

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobs.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1000
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=100
                    ),
                ),
                (
                    "export_formats",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        size=None,
                        validators=[jobs.models.validate_export_formats],
                    ),
                ),
                ("published", models.BooleanField(db_index=True, default=False)),
                (
                    "the_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        srid=4326, verbose_name="Uploaded geometry"
                    ),
                ),
                (
                    "simplified_geom",
                    django.contrib.gis.db.models.fields.GeometryField(
                        blank=True,
                        null=True,
                        srid=4326,
                        verbose_name="Simplified geometry",
                    ),
                ),
                (
                    "feature_selection",
                    models.TextField(
                        validators=[jobs.models.validate_feature_selection]
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("mbtiles_maxzoom", models.IntegerField(blank=True, null=True)),
                ("mbtiles_minzoom", models.IntegerField(blank=True, null=True)),
                ("mbtiles_source", models.TextField(blank=True, null=True)),
                ("buffer_aoi", models.BooleanField(default=False)),
                ("unlimited_extent", models.BooleanField(default=False)),
                ("hidden", models.BooleanField(default=False)),
                ("expire_old_runs", models.BooleanField(default=True)),
                ("pinned", models.BooleanField(default=False)),
                ("unfiltered", models.BooleanField(default=False)),
                ("preserve_geom", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owner",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "jobs",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="SavedFeatureSelection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=100)),
                (
                    "description",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=1000
                    ),
                ),
                (
                    "yaml",
                    models.TextField(
                        validators=[jobs.models.validate_feature_selection]
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("deleted", models.BooleanField(default=False)),
                (
                    "uid",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("pinned", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PartnerExportRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_period",
                    models.CharField(
                        choices=[
                            ("6hrs", "Every 6 hours"),
                            ("daily", "Every day"),
                            ("weekly", "Every Sunday"),
                            ("2wks", "Every two weeks"),
                            ("3wks", "Every three weeks"),
                            ("monthly", "The 1st of every month"),
                            ("quarterly", "Every quarter (90 days)"),
                            ("semiyearly", "Every 6 months"),
                            ("yearly", "Every year"),
                            ("disabled", "Disabled"),
                        ],
                        default="disabled",
                        max_length=10,
                    ),
                ),
                (
                    "schedule_hour",
                    models.IntegerField(
                        choices=[
                            (0, 0),
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                            (13, 13),
                            (14, 14),
                            (15, 15),
                            (16, 16),
                            (17, 17),
                            (18, 18),
                            (19, 19),
                            (20, 20),
                            (21, 21),
                            (22, 22),
                            (23, 23),
                        ],
                        default=0,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("planet_file", models.BooleanField(default=False)),
                ("polygon_centroid", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.job",
                    ),
                ),
            ],
            bases=(models.Model, jobs.models.RegionMixin),
        ),
        migrations.CreateModel(
            name="HDXExportRegion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "schedule_period",
                    models.CharField(
                        choices=[
                            ("6hrs", "Every 6 hours"),
                            ("daily", "Every day"),
                            ("weekly", "Every Sunday"),
                            ("2wks", "Every two weeks"),
                            ("3wks", "Every three weeks"),
                            ("monthly", "The 1st of every month"),
                            ("quarterly", "Every quarter (90 days)"),
                            ("semiyearly", "Every 6 months"),
                            ("yearly", "Every year"),
                            ("disabled", "Disabled"),
                        ],
                        default="disabled",
                        max_length=10,
                    ),
                ),
                ("schedule_hour", models.IntegerField(choices=[], default=0)),
                ("deleted", models.BooleanField(default=False)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "locations",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=32), null=True, size=None
                    ),
                ),
                ("license", models.CharField(blank=True, max_length=32, null=True)),
                ("subnational", models.BooleanField(default=True)),
                ("extra_notes", models.TextField(blank=True, null=True)),
                ("planet_file", models.BooleanField(default=False)),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hdx_export_region_set",
                        to="jobs.job",
                    ),
                ),
            ],
            options={
                "db_table": "hdx_export_regions",
            },
            bases=(models.Model, jobs.models.RegionMixin),
        ),
    ]
