# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-24 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    def add_gpkg_export_format(apps, schema_editor):
        ExportFormat = apps.get_model('jobs', 'ExportFormat')
        ExportFormat.objects.create(name='GeoPackage Format (OSM)', description='GeoPackage (OSM Schema)',
                                    slug='GPKG')
        ExportFormat.objects.create(name='GeoPackage Format (Thematic)', description='GeoPackage (Thematic Schema)',
                                    slug='THEME_GPKG')

    dependencies = [
        ('jobs', '0029_auto_20170323_2111'),
    ]

    operations = [
        migrations.RunPython(add_gpkg_export_format),
    ]
