# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-28 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_add_gpkg_export_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportconfig',
            name='config_type',
            field=models.CharField(choices=[('PRESET', 'Preset')], default='PRESET', max_length=11),
        ),
    ]
