# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 04:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_auto_20170328_2342'),
        ('jobs', '0031_convert_export_format_to_slug'),
    ]

    operations = [
    ]
