# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 16:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0033_job_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='configs',
        ),
    ]
