# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 14:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_remove_job_configs'),
    ]

    operations = [
        migrations.CreateModel(
            name='HDXExportRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset_prefix', models.CharField(max_length=100)),
                ('feature_selection', models.TextField()),
                ('schedule_period', models.CharField(choices=[('6hrs', 'Every 7 hours'), ('daily', 'Every day'), ('weekly', 'Every Sunday'), ('monthly', 'The 1st of every month'), ('disabled', 'Disabled')], default='disabled', max_length=10)),
                ('schedule_hour', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)])),
                ('export_formats', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('kml', 'Google Earth KMZ'), ('pbf', 'OSM PBF'), ('sqlite', 'SQLite Database'), ('geopackage', 'GeoPackage Format (OSM)'), ('theme_gpkg', 'GeoPackage (Thematic'), ('obf', 'OSMAnd OBF'), ('shp', 'ESRI Shapefile format (OSM)'), ('thematic', 'ESRI Shapefile format (Thematic)'), ('garmin', 'Garmin Map')], max_length=10), size=None)),
                ('the_geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Extent for export')),
            ],
        ),
    ]
