# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-30 21:34
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    def backfill_names(apps, schema_editor):
        HDXExportRegion = apps.get_model('jobs', 'HDXExportRegion')
        for region in HDXExportRegion.objects.all():
            region.name = region.dataset_prefix
            region.save()

    dependencies = [
        ('jobs', '0035_hdxexportregion'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdxexportregion',
            name='country_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), null=True, size=None),
        ),
        migrations.AddField(
            model_name='hdxexportregion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hdxexportregion',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hdxexportregion',
            name='schedule_hour',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], default=0),
        ),
        migrations.AlterField(
            model_name='hdxexportregion',
            name='schedule_period',
            field=models.CharField(choices=[('6hrs', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every Sunday'), ('monthly', 'The 1st of every month'), ('disabled', 'Disabled')], default='disabled', max_length=10),
        ),
        migrations.RunPython(backfill_names)
    ]
