# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-04 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_auto_20170330_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdxexportregion',
            name='last_run',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
