# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0037_hdxexportregion_last_run'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportprofile',
            name='group',
        ),
        migrations.DeleteModel(
            name='ExportProfile',
        ),
    ]
