# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-07 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_remove_hdxexportregion_dataset_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdxexportregion',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
