# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-19 21:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0042_auto_20170411_2155'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hdxexportregion',
            table='hdx_export_regions',
        ),
    ]
