# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 18:15
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0043_auto_20170419_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='the_geog',
        ),
        migrations.RemoveField(
            model_name='job',
            name='the_geom_webmercator',
        ),
        migrations.AlterField(
            model_name='job',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default='', srid=4326, verbose_name='Extent for export'),
        ),
    ]
