# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0044_auto_20170424_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdxexportregion',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdx_export_region_set', to='jobs.Job'),
        ),
    ]
