# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 22:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0045_auto_20170424_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='buffer_aoi',
            field=models.BooleanField(default=False),
        ),
    ]
