# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_job_buffer_aoi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportconfig',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='job',
        ),
        migrations.RemoveField(
            model_name='job',
            name='config',
        ),
        migrations.DeleteModel(
            name='ExportConfig',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
