# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 06:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_auto_20170522_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='feature_pub',
        ),
        migrations.RemoveField(
            model_name='job',
            name='feature_save',
        ),
    ]
