# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 08:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_auto_20170610_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='export_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, size=None, validators=[jobs.models.validate_export_formats]),
        ),
    ]
