# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 22:51
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0050_auto_20170610_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.CharField(blank=True, db_index=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='job',
            name='export_formats',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None, validators=[jobs.models.validate_export_formats]),
        ),
        migrations.AlterField(
            model_name='job',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, validators=[jobs.models.validate_aoi], verbose_name='Extent for export'),
        ),
    ]
