# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-12 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_auto_20170611_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdxexportregion',
            name='extra_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hdxexportregion',
            name='license',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
