# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '0053_auto_20170612_0313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFeatureSelection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('description', models.CharField(blank=True, db_index=True, default='', max_length=1000)),
                ('yaml', models.TextField(validators=[jobs.models.validate_feature_selection])),
                ('public', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
