# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-26 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0054_savedfeatureselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfeatureselection',
            name='uid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
