# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0055_savedfeatureselection_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='expire_old_runs',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='unlimited_extent',
            field=models.BooleanField(default=False),
        ),
    ]
