# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 19:38
from __future__ import unicode_literals

from django.db import migrations, models

def hdx_pertheme(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    HDXExportRegion = apps.get_model('jobs', 'HDXExportRegion')
    for region in HDXExportRegion.objects.all():
        job = region.job
        job.per_theme = True
        job.hidden = True
        job.unlimited_extent = True
        job.expire_old_runs = False
        job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0056_auto_20170628_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='per_theme',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(hdx_pertheme)
    ]
