# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-03 23:55
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations
import jobs.models
from jobs.models import simplify_geom


def simplify_geoms(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.all():
        job.simplified_geom = simplify_geom(job.the_geom)
        job.save()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0057_job_per_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='simplified_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True,blank=True, srid=4326, verbose_name='Simplified geometry'),
        ),
        migrations.AlterField(
            model_name='job',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, validators=[jobs.models.validate_aoi], verbose_name='Uploaded geometry'),
        ),
        migrations.RunPython(simplify_geoms)
    ]
