# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:43
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0059_auto_20170711_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='the_geom',
            field=django.contrib.gis.db.models.fields.GeometryField(srid=4326, verbose_name='Uploaded geometry'),
        ),
    ]
