# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0060_auto_20170825_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='mbtiles_maxzoom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mbtiles_minzoom',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='mbtiles_source',
            field=models.TextField(null=True),
        ),
    ]
