# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-25 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0061_auto_20170825_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedfeatureselection',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='mbtiles_maxzoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='mbtiles_minzoom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='mbtiles_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
