# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('jobs', '0062_auto_20170925_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerExportRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_period', models.CharField(choices=[('6hrs', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every Sunday'), ('monthly', 'The 1st of every month'), ('disabled', 'Disabled')], default='disabled', max_length=10)),
                ('schedule_hour', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23)], default=0)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.Job')),
            ],
        ),
        migrations.AlterField(
            model_name='hdxexportregion',
            name='schedule_hour',
            field=models.IntegerField(default=0),
        ),
    ]
