# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0063_auto_20190814_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerexportregion',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
