# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-20 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0064_partnerexportregion_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdxexportregion',
            name='planet_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='partnerexportregion',
            name='planet_file',
            field=models.BooleanField(default=False),
        ),
    ]
