# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-12 02:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0065_auto_20191020_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
