# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 20:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0066_job_pinned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='per_theme',
        ),
    ]
