# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-11-19 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0067_remove_job_per_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='unfiltered',
            field=models.BooleanField(default=False),
        ),
    ]
