# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-22 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0068_job_unfiltered'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerexportregion',
            name='polygon_centroid',
            field=models.BooleanField(default=False),
        ),
    ]
