# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-29 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0069_partnerexportregion_polygon_centroid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdxexportregion',
            name='schedule_period',
            field=models.CharField(choices=[('6hrs', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every Sunday'), ('two_weeks', 'Every two weeks'), ('three_weeks', 'Every three weeks'), ('monthly', 'The 1st of every month'), ('disabled', 'Disabled')], default='disabled', max_length=10),
        ),
        migrations.AlterField(
            model_name='partnerexportregion',
            name='schedule_period',
            field=models.CharField(choices=[('6hrs', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every Sunday'), ('two_weeks', 'Every two weeks'), ('three_weeks', 'Every three weeks'), ('monthly', 'The 1st of every month'), ('disabled', 'Disabled')], default='disabled', max_length=10),
        ),
    ]
