# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-09 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0070_auto_20210129_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hdxexportregion',
            name='schedule_period',
            field=models.CharField(choices=[('6hrs', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every Sunday'), ('2wks', 'Every two weeks'), ('3wks', 'Every three weeks'), ('monthly', 'The 1st of every month'), ('disabled', 'Disabled')], default='disabled', max_length=10),
        ),
        migrations.AlterField(
            model_name='partnerexportregion',
            name='schedule_period',
            field=models.CharField(choices=[('6hrs', 'Every 6 hours'), ('daily', 'Every day'), ('weekly', 'Every Sunday'), ('2wks', 'Every two weeks'), ('3wks', 'Every three weeks'), ('monthly', 'The 1st of every month'), ('disabled', 'Disabled')], default='disabled', max_length=10),
        ),
    ]
