# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-07 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0071_auto_20210209_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='preserve_geom',
            field=models.BooleanField(default=False),
        ),
    ]
