# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-11-19 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0073_auto_20221115_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdxexportregion',
            name='country_export',
            field=models.BooleanField(default=False),
        ),
    ]
