# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-12-01 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0074_hdxexportregion_country_export'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdxexportregion',
            name='sync_status',
            field=models.BooleanField(default=False),
        ),
    ]
