# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2023-03-23 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0077_auto_20221203_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdxexportregion',
            name='country_export',
        ),
    ]
