# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 20:29
from __future__ import unicode_literals

from django.db import migrations
from oauth2_provider.models import Application


class Migration(migrations.Migration):
    def add_default_application(apps, schema_editor):
        Application.objects.create(
            name="OSM Export Tool UI",
            redirect_uris="http://localhost/authorized",
            client_type=Application.CLIENT_PUBLIC,
            authorization_grant_type=Application.GRANT_IMPLICIT,
            skip_authorization=True)

    dependencies = [
        ("oauth2_provider", "0005_auto_20170514_1141"),
    ]

    operations = [
        migrations.RunPython(add_default_application),
    ]
