# Generated by Django 3.2.22 on 2023-10-31 04:36

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobs', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('worker_message_id', models.CharField(blank=True, editable=False, max_length=50, null=True)),
                ('hdx_sync_status', models.BooleanField(default=False)),
                ('status', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('started_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='jobs.job')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_runs',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportTask',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(blank=True, db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('started_at', models.DateTimeField(editable=False, null=True)),
                ('finished_at', models.DateTimeField(editable=False, null=True)),
                ('filesize_bytes', models.BigIntegerField(null=True)),
                ('filenames', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), default=list, size=None)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.exportrun')),
            ],
            options={
                'db_table': 'export_tasks',
                'ordering': ['created_at'],
            },
        ),
    ]
