# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-29 01:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0027_exportrun_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttaskexception',
            name='task',
        ),
        migrations.DeleteModel(
            name='ExportTaskException',
        ),
    ]
