# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 00:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0028_auto_20170329_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttask',
            name='celery_uid',
        ),
    ]
