# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0029_remove_exporttask_celery_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exporttaskresult',
            name='task',
        ),
        migrations.AddField(
            model_name='exporttask',
            name='filesize_bytes',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='ExportTaskResult',
        ),
    ]
