# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-06 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0030_auto_20170406_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='exporttask',
            name='filename',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
