# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-24 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0033_remove_exporttask_filename'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportrun',
            options={},
        ),
    ]
