# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-22 22:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0035_auto_20170424_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exportrun',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='exporttask',
            options={'ordering': ['created_at']},
        ),
    ]
