# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-07 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0036_auto_20170522_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exporttask',
            name='filesize_bytes',
            field=models.BigIntegerField(null=True),
        ),
    ]
