# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-11-15 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0037_auto_20221107_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='worker_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
