# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-11-15 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0038_exportrun_worker_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrun',
            name='worker_message_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
