# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-12-01 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0039_auto_20221115_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportrun',
            name='started_at',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
