# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2022-12-01 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0040_auto_20221201_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportrun',
            name='hdx_sync_status',
            field=models.BooleanField(default=False),
        ),
    ]
