#!/bin/sh

### BEGIN INIT INFO
# Provides:             overpass
# Required-Start:       $remote_fs $syslog
# Required-Stop:        $remote_fs $syslog
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    Overpass API dispatcher daemon
### END INIT INFO

DB_DIR=/srv/osm3s/db
EXEC_DIR=/srv/osm3s

LOG_DIR=/var/log/overpass
RUN_AS_USER=root

mkdir $LOG_DIR 2>/dev/null

DISPATCHER_PID_FILE=/var/run/dispatcher.pid
DISPATCHER_OPTIONS="--osm-base --db-dir=$DB_DIR"
DISPATCHER=$EXEC_DIR/bin/dispatcher

test -x $DISPATCHER || exit 0
. /lib/lsb/init-functions

case "$1" in
  start)
    log_daemon_msg "Starting Overpass dispatcher daemon" "dispatcher"
    if test -f $DISPATCHER_PID_FILE; then
      echo "dispatcher already running?"
      exit 1
    fi
    rm $DB_DIR/osm3s* 2>/dev/null
    rm /dev/shm/osm3s* 2>/dev/null
    if start-stop-daemon --start --quiet -b --oknodo --make-pidfile -c $RUN_AS_USER --pidfile $DISPATCHER_PID_FILE --exec $DISPATCHER -- $DISPATCHER_OPTIONS >> $LOG_DIR/dispatcher.log 2>&1; then
      mkdir /tmp/translate_xapi 2>/dev/null
      chmod 777 /tmp/translate_xapi
      log_end_msg 0
    else
      log_end_msg 1
    fi 
    ;;

  stop)
    log_daemon_msg "Stopping Overpass dispatcher daemon" "dispatcher"
    if start-stop-daemon --stop --quiet --oknodo --pidfile $DISPATCHER_PID_FILE; then
      log_end_msg 0
      rm $DB_DIR/osm3s* 2>/dev/null
      rm /dev/shm/osm3s* 2>/dev/null
      rm -f $DISPATCHER_PID_FILE
    else
      log_end_msg 1
    fi
    ;;

  status)
    status_of_proc -p $DISPATCHER_PID_FILE "" "overpass dispatcher"
    ;;

  *)
    log_action_msg "Usage: /etc/init.d/overpass {start|stop|status}"
    exit 1
esac

exit 0
